FROM node:16-alpine3.12

LABEL version="1.0"
LABEL description="React frontend for the Real Estate API"

WORKDIR /app

COPY ./package*.json ./

# RUN npm i -g yarn 

RUN yarn install

COPY . .

CMD ["yarn","run", "start"]