# Generated by Django 2.2.3 on 2019-08-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_projects_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('Completed', 'Complete'), ('Ongoing', 'Ongoing')], default='completed', help_text='Status of the project', max_length=100),
        ),
    ]
