# Generated by Django 2.2.3 on 2019-08-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190824_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='EndDate',
            field=models.DateTimeField(blank=True, help_text='End date', null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='StartDate',
            field=models.DateTimeField(auto_now_add=True, help_text='Start Date'),
        ),
    ]
