# Generated by Django 2.2.3 on 2019-08-27 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190824_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyName', models.CharField(help_text='The Name of the property', max_length=255)),
                ('Address', models.CharField(help_text='The address of the above property', max_length=255)),
                ('City', models.CharField(help_text='The city where the property is located', max_length=255)),
                ('County', models.CharField(help_text='The county of the city above', max_length=100)),
                ('Picture1', models.ImageField(help_text='Attach first image of your property', upload_to='')),
                ('Picture2', models.ImageField(blank=True, help_text='Attach second image of your property', null=True, upload_to='')),
                ('Picture3', models.ImageField(blank=True, help_text='Attach third image of your property', null=True, upload_to='')),
                ('Picture4', models.ImageField(blank=True, help_text='Attach fourth image of your property', null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='lease',
            name='PropertyID',
            field=models.ForeignKey(help_text='Property nae', on_delete=django.db.models.deletion.CASCADE, to='blog.Properties'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='StartDate',
            field=models.DateTimeField(auto_now_add=True, help_text='Contract Deadline'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='TenantID',
            field=models.ForeignKey(help_text='Start Date', on_delete=django.db.models.deletion.CASCADE, to='blog.Tenant'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='UnitID',
            field=models.ForeignKey(help_text='The unit to let ', on_delete=django.db.models.deletion.CASCADE, to='blog.Units'),
        ),
    ]
