# Generated by Django 2.2.3 on 2019-08-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyName', models.CharField(help_text='The Name of the property', max_length=255)),
                ('Address', models.CharField(help_text='The address of the above property', max_length=255)),
                ('City', models.CharField(help_text='The city where the property is located', max_length=255)),
                ('County', models.CharField(help_text='The county of the city above', max_length=100)),
                ('Picture1', models.ImageField(help_text='Attach first image of your property', upload_to='')),
                ('Picture2', models.ImageField(blank=True, help_text='Attach second image of your property', null=True, upload_to='')),
                ('Picture3', models.ImageField(blank=True, help_text='Attach third image of your property', null=True, upload_to='')),
                ('Picture4', models.ImageField(blank=True, help_text='Attach fourth image of your property', null=True, upload_to='')),
            ],
        ),
    ]
